#!/bin/bash
cp main.cpp gdb
cp src/Server.cpp gdb
cp include/Server.h gdb
cp src/ServerSock.cpp gdb
cp include/ServerSock.h gdb
cp src/ServerFile.cpp gdb
cp include/ServerFile.h gdb
echo "compiling"
g++ gdb/*.cpp -o gdb/test -g
echo "opening gdb"
gdb gdb/test

